//! Construction of the canonical Akron CompiledProgram boundary.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use akron::CompiledProgram;
use memory::field::PrimeId;
use memory::Function;

use crate::{Compiler, CompilerError};

/// Inputs that affect source resolution or generated bytecode.
#[derive(Debug, Clone)]
pub struct CompileOptions {
    pub source_path: Option<PathBuf>,
    pub prime_id: PrimeId,
    pub circom_lib_dirs: Vec<PathBuf>,
}

impl Default for CompileOptions {
    fn default() -> Self {
        Self {
            source_path: None,
            prime_id: PrimeId::Bn254,
            circom_lib_dirs: Vec::new(),
        }
    }
}

impl CompileOptions {
    pub fn for_source(path: impl Into<PathBuf>) -> Self {
        Self {
            source_path: Some(path.into()),
            ..Self::default()
        }
    }

    pub fn with_prime(mut self, prime_id: PrimeId) -> Self {
        self.prime_id = prime_id;
        self
    }

    pub fn with_circom_lib_dirs(mut self, dirs: Vec<PathBuf>) -> Self {
        self.circom_lib_dirs = dirs;
        self
    }

    fn apply(&self, compiler: &mut Compiler) {
        compiler.prime_id = self.prime_id;
        compiler.circom_lib_dirs = self.circom_lib_dirs.clone();
        compiler.base_path = self.source_path.as_deref().map(source_parent);
        if let Some(source_path) = &self.source_path {
            if let Ok(canonical) = source_path.canonicalize() {
                compiler.compiling_modules.insert(canonical);
            }
        }
    }
}

fn source_parent(path: &Path) -> PathBuf {
    path.parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or_else(|| Path::new("."))
        .to_path_buf()
}

impl Compiler {
    /// Compile source into the owned representation consumed by every engine.
    ///
    /// The existing compile method remains available for low-level callers.
    /// New execution and artifact paths should use this method so source
    /// resolution, prime selection, tables, line info and capabilities cannot
    /// drift.
    pub fn compile_program(
        &mut self,
        source: &str,
        options: &CompileOptions,
    ) -> Result<CompiledProgram, CompilerError> {
        options.apply(self);
        let bytecode = self.compile(source)?;
        let main = self
            .compilers
            .last()
            .ok_or_else(|| CompilerError::InternalError("compiler has no main function".into()))?;

        let debug_symbols: HashMap<u16, String> = self
            .global_symbols
            .iter()
            .map(|(name, entry)| (entry.index, name.clone()))
            .collect();

        let mut program = CompiledProgram::new(
            self.prime_id,
            self.interner.strings.clone(),
            self.field_interner.fields.clone(),
            self.bigint_interner.bigints.clone(),
            self.bytes_interner.blobs.clone(),
            self.circom_handle_interner.handles.clone(),
            self.prototypes.clone(),
            Function {
                name: "main".to_string(),
                arity: 0,
                max_slots: main.max_slots,
                chunk: bytecode,
                constants: main.constants.clone(),
                upvalue_info: Vec::new(),
                line_info: main.line_info.clone(),
            },
            debug_symbols,
        );
        program.register_native_registry(&self.native_registry);
        program.record_inferred_effects(self.inferred_effects);
        program.validate().map_err(|error| {
            CompilerError::InternalError(format!(
                "compiler produced an invalid CompiledProgram: {error}"
            ))
        })?;
        Ok(program)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use akron::specs::{CapabilitySet, EffectSet};
    use akron::ProgramCapabilities;
    use std::io::Cursor;
    use std::io::Write;

    #[test]
    fn compile_program_uses_source_directory_for_imports() {
        let directory = tempfile::tempdir().unwrap();
        let module = directory.path().join("module.ach");
        let main = directory.path().join("main.ach");
        std::fs::write(&module, "export fn answer() { 42 }").unwrap();

        let source = "import \"./module.ach\" as m\nprint(m::answer())";
        let mut file = std::fs::File::create(&main).unwrap();
        file.write_all(source.as_bytes()).unwrap();

        let mut compiler = Compiler::new();
        let program = compiler
            .compile_program(source, &CompileOptions::for_source(&main))
            .unwrap();
        assert!(!program.main.chunk.is_empty());
        assert!(!program.functions.is_empty());
    }

    #[test]
    fn compile_program_preserves_line_tables() {
        let mut compiler = Compiler::new();
        let program = compiler
            .compile_program("let x = 1\nprint(x)", &CompileOptions::default())
            .unwrap();
        assert_eq!(program.main.chunk.len(), program.main.line_info.len());
        for function in &program.functions {
            assert_eq!(function.chunk.len(), function.line_info.len());
        }
    }

    #[test]
    fn compile_program_validates_structured_task_bytecode_and_capabilities() {
        let source = "fn answer() { 42 }\n\
                      let result = concurrent { let task = spawn answer(); await task }";
        let mut compiler = Compiler::new();
        let program = compiler
            .compile_program(source, &CompileOptions::default())
            .unwrap();

        program.validate().unwrap();
        assert!(program
            .capabilities
            .contains(akron::ProgramCapabilities::TASKS));
        assert_eq!(program.bytecode_version, akron::BYTECODE_VERSION);
        assert_eq!(program.format_version, akron::EXECUTABLE_FORMAT_VERSION);
    }

    #[test]
    fn unresolved_dynamic_call_preserves_uncertainty_without_inventing_authority() {
        let source = "fn invoke(f) { f() }\ninvoke(time)";
        let mut compiler = Compiler::new();
        let program = compiler
            .compile_program(source, &CompileOptions::default())
            .unwrap();

        assert!(program
            .requested_effects()
            .contains(EffectSet::UNKNOWN_HOST));
        assert_eq!(program.requested_host_capabilities(), CapabilitySet::CLOCK);
        assert!(program
            .capabilities
            .contains(ProgramCapabilities::UNKNOWN_HOST));

        let mut bytes = Vec::new();
        program.write_executable(&mut bytes).unwrap();
        let decoded = akron::CompiledProgram::read_executable(&mut Cursor::new(bytes)).unwrap();
        assert!(decoded
            .requested_effects()
            .contains(EffectSet::UNKNOWN_HOST));
        assert_eq!(decoded.requested_host_capabilities(), CapabilitySet::CLOCK);
    }

    #[test]
    fn pure_dynamic_call_requests_no_host_authority() {
        let source = "fn invoke(f) { f() }\ninvoke(fn() { 1 })";
        let mut compiler = Compiler::new();
        let program = compiler
            .compile_program(source, &CompileOptions::default())
            .unwrap();

        assert!(program
            .requested_effects()
            .contains(EffectSet::UNKNOWN_HOST));
        assert!(program
            .capabilities
            .contains(ProgramCapabilities::UNKNOWN_HOST));
        assert_eq!(
            program.requested_host_capabilities(),
            CapabilitySet::empty()
        );
    }
}
